//! R7 (`docs/design/cli-output-contract.md` §4, tracker #3314 S5): prose does
//! not get to invent CLI output.
//!
//! The reference pages under `generated/docs/` derive their transcripts from
//! `command-examples.json`, so they cannot drift. Hand-written prose — the
//! README that ships inside every binary tarball, the agent skill, everything
//! under `docs/` — can, and has: a `# pong 1.1.0` outlived two releases. So
//! every fenced transcript here is held to the captured examples. A fence
//! whose output cannot be checked says so out loud, with `<!-- illustrative
//! -->` on the line above it, which is one grep away for a reviewer instead of
//! being indistinguishable from a real capture.
//!
//! The clap-parse guard (the resolver plan's S4a) already proves prose
//! *inputs* parse. This is the output half.

#![deny(unsafe_code)]

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde::Deserialize;

/// Marks a fence whose output is written by hand rather than captured — a
/// sketch of a shape, a machine-specific path, a feature being designed.
const ILLUSTRATIVE: &str = "<!-- illustrative -->";

/// The one Markdown file under `docs/` that is *not* prose: the contract
/// matrix is a rendering of the cells themselves, regenerated by blessing the
/// snapshot corpus, so holding it against the captures would be circular.
const NOT_PROSE: &[&str] = &["docs/design/cli-output-catalog.md"];

/// A captured step, read for the two fields this guard compares against
/// prose; the artifact carries more, which serde ignores.
#[derive(Deserialize)]
struct CapturedStep {
    #[serde(rename = "in")]
    input: String,
    out: String,
}

#[derive(Deserialize)]
struct Captures {
    commands: BTreeMap<String, Vec<CapturedStep>>,
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// Every captured CLI line and the output it produced. One line can appear in
/// several examples (`strata kv put greeting hello` opens more than one), so
/// the value is the set of outputs seen for it — prose matching any of them is
/// showing something the binary really printed.
fn captured_outputs() -> BTreeMap<String, Vec<String>> {
    let path = repo_root().join("crates/executor/idl/v1/generated/command-examples.json");
    let captures: Captures = serde_json::from_str(
        &std::fs::read_to_string(&path).expect("command-examples.json exists"),
    )
    .expect("command-examples.json parses");
    let mut by_input: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for step in captures.commands.into_values().flatten() {
        let outputs = by_input.entry(step.input).or_default();
        if !outputs.contains(&step.out) {
            outputs.push(step.out);
        }
    }
    by_input
}

/// The prose surfaces a reader can copy from: the packaged README, the agent
/// skill, and the documentation tree.
fn prose_files() -> Vec<PathBuf> {
    let root = repo_root();
    let mut files = vec![
        root.join("README.md"),
        root.join("crates/cli/src/agents_skill.md"),
    ];
    let mut stack = vec![root.join("docs")];
    while let Some(dir) = stack.pop() {
        for entry in std::fs::read_dir(&dir).expect("docs dir is readable") {
            let path = entry.expect("dir entry").path();
            if path.is_dir() {
                stack.push(path);
            } else if path.extension().is_some_and(|ext| ext == "md")
                && !NOT_PROSE.iter().any(|skip| path.ends_with(skip))
            {
                files.push(path);
            }
        }
    }
    files.sort();
    files
}

/// A fenced code block, with the line it opens on and whether the line above
/// it declares the block illustrative.
struct Fence {
    line: usize,
    illustrative: bool,
    body: Vec<String>,
}

fn fences(text: &str) -> Vec<Fence> {
    let lines: Vec<&str> = text.lines().collect();
    let mut fences = Vec::new();
    let mut index = 0;
    while index < lines.len() {
        if !lines[index].trim_start().starts_with("```") {
            index += 1;
            continue;
        }
        let opened_at = index;
        // A fence nested in a list item is indented, and so is everything in
        // it. Reading it at column zero would leave every line prefixed with
        // that indent, matching no capture — a transcript that quietly opts out
        // of this guard by being one bullet deep.
        let indent =
            &lines[opened_at][..lines[opened_at].len() - lines[opened_at].trim_start().len()];
        let mut body = Vec::new();
        index += 1;
        while index < lines.len() && !lines[index].trim_start().starts_with("```") {
            body.push(
                lines[index]
                    .strip_prefix(indent)
                    .unwrap_or(lines[index])
                    .to_owned(),
            );
            index += 1;
        }
        fences.push(Fence {
            line: opened_at + 1,
            illustrative: opened_at > 0 && lines[opened_at - 1].trim() == ILLUSTRATIVE,
            body,
        });
        index += 1;
    }
    fences
}

/// One `$ …` line and everything printed under it, up to the next prompt.
struct Exchange {
    input: String,
    output: String,
}

/// Splits a fence into exchanges. A fence with no `$ ` prompt shows no output
/// — it is a script to run, not a transcript — and yields nothing.
fn exchanges(body: &[String]) -> Vec<Exchange> {
    let mut exchanges: Vec<Exchange> = Vec::new();
    for line in body {
        if let Some(input) = line.strip_prefix("$ ") {
            // A trailing `# …` is the author talking, not output.
            let input = input.split("  #").next().unwrap_or(input).trim_end();
            exchanges.push(Exchange {
                input: input.to_owned(),
                output: String::new(),
            });
        } else if let Some(current) = exchanges.last_mut() {
            if !current.output.is_empty() {
                current.output.push('\n');
            }
            current.output.push_str(line);
        }
    }
    for exchange in &mut exchanges {
        exchange.output = exchange.output.trim_end().to_owned();
    }
    exchanges
}

#[test]
fn prose_transcripts_show_what_the_binary_prints() {
    let captured = captured_outputs();
    let root = repo_root();
    let mut unverifiable = Vec::new();
    let mut wrong = Vec::new();
    for path in prose_files() {
        let text = std::fs::read_to_string(&path).expect("prose file is readable");
        let shown = path.strip_prefix(&root).unwrap_or(&path).display();
        for fence in fences(&text) {
            if fence.illustrative {
                continue;
            }
            for exchange in exchanges(&fence.body) {
                if exchange.output.is_empty() || !exchange.input.starts_with("strata") {
                    continue;
                }
                let Some(outputs) = captured.get(&exchange.input) else {
                    unverifiable.push(format!(
                        "{shown}:{} `{}` is not a captured example, so its output cannot be \
                         checked",
                        fence.line, exchange.input
                    ));
                    continue;
                };
                if !outputs.contains(&exchange.output) {
                    wrong.push(format!(
                        "{shown}:{} `{}` prints\n---\n{}\n---\nbut the docs show\n---\n{}\n---",
                        fence.line,
                        exchange.input,
                        outputs.join("\n--- or ---\n"),
                        exchange.output
                    ));
                }
            }
        }
    }
    assert!(
        wrong.is_empty(),
        "prose shows output the binary does not print:\n\n{}",
        wrong.join("\n\n")
    );
    assert!(
        unverifiable.is_empty(),
        "prose shows output for a command with no captured example:\n  {}\n\nEither use a \
         command the examples cover, add an example for it under \
         `crates/executor/idl/v1/examples/`, or put `{ILLUSTRATIVE}` on the line above the \
         fence to say the output is hand-written.",
        unverifiable.join("\n  ")
    );
}

#[test]
fn a_version_printed_in_prose_is_the_version_being_built() {
    let version = env!("CARGO_PKG_VERSION");
    let root = repo_root();
    let mut stale = Vec::new();
    for path in prose_files() {
        let text = std::fs::read_to_string(&path).expect("prose file is readable");
        let shown = path.strip_prefix(&root).unwrap_or(&path).display();
        for fence in fences(&text) {
            for (offset, line) in fence.body.iter().enumerate() {
                if !line.contains("strata ") {
                    continue;
                }
                let Some((_, comment)) = line.split_once('#') else {
                    continue;
                };
                for claimed in comment.split_whitespace().filter(|word| is_version(word)) {
                    if claimed != version {
                        stale.push(format!(
                            "{shown}:{} claims `{claimed}`",
                            fence.line + offset + 1
                        ));
                    }
                }
            }
        }
    }
    assert!(
        stale.is_empty(),
        "prose shows a version the binary no longer prints (this build is {version}):\n  {}\n\n\
         A release bumps these with the workspace version — the README ships inside every \
         binary tarball.",
        stale.join("\n  ")
    );
}

/// Whether a word in an output comment is a version — `1.2.1`, or `1.2.1.` at
/// the end of a sentence. Deliberately narrow: a bare `1.2` or a date is not
/// a version claim.
fn is_version(word: &str) -> bool {
    let word = word.trim_end_matches(['.', ',', ')', ';']);
    let mut parts = word.split('.');
    let numeric = |part: Option<&str>| {
        part.is_some_and(|part| !part.is_empty() && part.chars().all(|c| c.is_ascii_digit()))
    };
    numeric(parts.next())
        && numeric(parts.next())
        && numeric(parts.next())
        && parts.next().is_none()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_prompt_line_starts_an_exchange_and_the_lines_under_it_are_its_output() {
        let parsed = exchanges(&[
            "$ strata kv get greeting".to_owned(),
            "hello".to_owned(),
            "$ strata kv get absent".to_owned(),
            "(nil)".to_owned(),
        ]);
        assert_eq!(parsed.len(), 2);
        assert_eq!(parsed[0].input, "strata kv get greeting");
        assert_eq!(parsed[0].output, "hello");
        assert_eq!(parsed[1].output, "(nil)");
    }

    #[test]
    fn a_script_without_prompts_claims_no_output() {
        assert!(exchanges(&["strata init".to_owned(), "strata kv put a b".to_owned()]).is_empty());
    }

    #[test]
    fn an_authors_comment_is_not_part_of_the_command() {
        let parsed = exchanges(&[
            "$ strata branch list  # after the fork".to_owned(),
            "NAME".to_owned(),
        ]);
        assert_eq!(parsed[0].input, "strata branch list");
    }

    #[test]
    fn a_fence_indented_under_a_list_item_is_read_at_its_own_margin() {
        let nested =
            fences("1. Try it:\n\n   ```console\n   $ strata kv get greeting\n   hello\n   ```\n");
        assert_eq!(nested.len(), 1);
        let parsed = exchanges(&nested[0].body);
        assert_eq!(parsed[0].input, "strata kv get greeting");
        assert_eq!(
            parsed[0].output, "hello",
            "the indent is the list's, not the output's"
        );
    }

    #[test]
    fn a_fence_is_illustrative_only_when_the_line_above_says_so() {
        let marked = fences("<!-- illustrative -->\n```console\n$ strata ping\npong\n```\n");
        assert!(marked[0].illustrative);
        let bare = fences("Some prose.\n```console\n$ strata ping\npong\n```\n");
        assert!(!bare[0].illustrative);
    }

    #[test]
    fn only_a_three_part_number_reads_as_a_version() {
        assert!(is_version("1.2.1"));
        assert!(is_version("1.2.1."));
        assert!(!is_version("1.2"));
        assert!(!is_version("2026-09-12"));
        assert!(!is_version("v1.2.1"));
    }
}
