//! TCP4.1 — per-command conformance test generation.
//!
//! Emits `crates/executor/tests/generated/conformance_cases.rs` from the
//! resolved command index: one test per command per applicable family, thin
//! calls into the hand-written `support` module beside it. Families:
//!
//! 1. **Wire round-trip idempotence** — every request fixture parses as
//!    [`Command`] and every response fixture as [`Output`], and one
//!    serialize→parse→serialize cycle is a fixed point (catches asymmetric
//!    serde impls that a one-directional replay never sees).
//! 2. **Nested unknown-key rejection** — at generation time the request
//!    fixture is walked alongside its derived JSON Schema; every object node
//!    whose subschema is closed (`additionalProperties: false`) becomes an
//!    injection site the test mutates and asserts the parse rejects. This is
//!    the #2705/#2696 class (`deny_unknown_fields` tested only at the
//!    top-level `Command`) made recursive, and sites are explicit in the
//!    generated file so a reviewer can see exactly what is asserted.
//! 3. **Declared error-envelope replay** — every authored `error_cases`
//!    fixture replays and its five stable envelope fields must match.
//! 4. **Observed-output ⊆ declared** — a replayed command's output `type` tag
//!    must be one the command's response fixtures declare (#2596: an output
//!    variant the IDL does not document). Its reach grows as later 4.1
//!    increments add generated inputs beyond the authored fixtures.
//!
//! `check-tests` is the drift guard: the committed file must byte-match a
//! fresh in-memory generation, mirroring `check`'s freshness contract.

// The emitter builds source text by appending formatted fragments; `push_str`
// + `format!` reads as the template it is, and the infallible `write!`
// alternative would force `.expect` noise at every site.
#![allow(clippy::format_push_string)]

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Deserialize;
use serde_json::Value;

use super::{invalid, CommandIndex, IdlError, ResolvedCommand, Result};
use crate::Command;

/// Repo-relative path of the emitted file.
const GENERATED_TESTS_REL: &str = "crates/executor/tests/generated/conformance_cases.rs";
/// Repo-relative path of the shrink-only schema/deserializer divergence ledger.
const DIVERGENCES_REL: &str = "crates/executor/idl/v1/unknown-key-divergences.yaml";

/// One (command, site) pair where the published schema is closed but the
/// deserializer accepts unknown keys — a filed wire-contract bug the
/// unknown-key family must skip until fixed.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct KnownDivergence {
    command: String,
    site: String,
    issue: u64,
}

fn read_divergences(repo_root: &Path) -> Result<Vec<KnownDivergence>> {
    let path = repo_root.join(DIVERGENCES_REL);
    let text = fs::read_to_string(&path).map_err(|source| IdlError::Read {
        path: path.clone(),
        source,
    })?;
    serde_yaml::from_str(&text).map_err(|source| IdlError::Yaml { path, source })
}

pub(super) fn generated_tests_path(repo_root: &Path) -> PathBuf {
    repo_root.join(GENERATED_TESTS_REL)
}

/// Renders the full generated-test source for `index`.
pub(super) fn generated_tests_source(
    repo_root: &Path,
    index: &CommandIndex,
    schema_documents: &BTreeMap<String, Value>,
) -> Result<String> {
    let fixtures_root = repo_root.join("crates/executor/tests/fixtures");
    let divergences = read_divergences(repo_root)?;
    let mut divergence_used = vec![false; divergences.len()];
    let mut out = String::new();
    out.push_str(
        "//! GENERATED by `strata-idl generate-tests` — do not hand-edit.\n\
         //! Regenerate after any IDL change; `check-tests` fails CI on drift.\n\
         //! One test per command per applicable conformance family; the\n\
         //! assertion logic lives in the hand-written `support` module.\n\
         #![allow(clippy::too_many_lines)]\n\n\
         use super::support;\n",
    );

    for entry in &index.commands {
        emit_command(
            &mut out,
            entry,
            schema_documents.get(&entry.id),
            &fixtures_root,
            &divergences,
            &mut divergence_used,
        )?;
    }
    for (entry, used) in divergences.iter().zip(&divergence_used) {
        if !used {
            return Err(invalid(format!(
                "unknown-key-divergences.yaml: entry `{}` site {:?} (#{}) matched no computed \
                 injection site — the command is gone or the schema opened; delete the entry",
                entry.command, entry.site, entry.issue
            )));
        }
    }
    Ok(out)
}

/// Generates the conformance test file.
pub fn generate_tests(repo_root: &Path) -> Result<()> {
    let index = super::resolve_index(repo_root)?;
    let documents = super::schemas::schema_documents(&index)?;
    let source = generated_tests_source(repo_root, &index, &documents)?;
    let path = generated_tests_path(repo_root);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|source| IdlError::Write {
            path: parent.to_path_buf(),
            source,
        })?;
    }
    fs::write(&path, source).map_err(|source| IdlError::Write { path, source })?;
    Ok(())
}

/// Fails when the committed conformance test file is stale.
pub fn check_tests(repo_root: &Path) -> Result<()> {
    let index = super::resolve_index(repo_root)?;
    let documents = super::schemas::schema_documents(&index)?;
    let expected = generated_tests_source(repo_root, &index, &documents)?;
    let path = generated_tests_path(repo_root);
    let actual = fs::read_to_string(&path).map_err(|source| IdlError::Read {
        path: path.clone(),
        source,
    })?;
    if actual != expected {
        return Err(IdlError::Stale { path });
    }
    Ok(())
}

fn emit_command(
    out: &mut String,
    entry: &ResolvedCommand,
    schema: Option<&Value>,
    fixtures_root: &Path,
    divergences: &[KnownDivergence],
    divergence_used: &mut [bool],
) -> Result<()> {
    let fn_base = entry.id.replace(['.', '-'], "_");

    out.push_str(&format!("\n// ---- {} ----\n", entry.id));

    // Family 1: request + response wire round-trip idempotence.
    out.push_str(&format!(
        "\n#[test]\nfn {fn_base}_request_wire_roundtrip_is_idempotent() {{\n    \
         support::request_roundtrip_idempotent({:?});\n}}\n",
        entry.fixtures.request
    ));
    for (position, response) in response_fixtures(entry).iter().enumerate() {
        let suffix = if position == 0 {
            String::new()
        } else {
            format!("_alt{position}")
        };
        out.push_str(&format!(
            "\n#[test]\nfn {fn_base}_response{suffix}_wire_roundtrip_is_idempotent() {{\n    \
             support::response_roundtrip_idempotent({response:?});\n}}\n"
        ));
    }

    // Family 2: nested unknown-key rejection at schema-closed object sites.
    // Sites on the shrink-only divergence ledger (#2739 class) are skipped —
    // and each ledger entry is re-verified to still BE a divergence, so a
    // fixed site forces its entry's deletion.
    if let Some(document) = schema {
        let sites = closed_object_sites(entry, document, fixtures_root)?;
        let fixture = read_fixture(fixtures_root, &entry.fixtures.request)?;
        let mut asserted = Vec::new();
        for site in sites {
            let listed = divergences
                .iter()
                .position(|entry_ref| entry_ref.command == entry.id && entry_ref.site == site);
            if let Some(position) = listed {
                divergence_used[position] = true;
                let divergence = &divergences[position];
                if !unknown_key_is_accepted(&fixture, &site) {
                    return Err(invalid(format!(
                        "unknown-key-divergences.yaml: `{}` site {site:?} now REJECTS unknown \
                         keys — #{} is fixed here; delete the entry (shrink-only)",
                        entry.id, divergence.issue
                    )));
                }
            } else {
                asserted.push(site);
            }
        }
        if !asserted.is_empty() {
            let list = asserted
                .iter()
                .map(|site| format!("{site:?}"))
                .collect::<Vec<_>>()
                .join(", ");
            out.push_str(&format!(
                "\n#[test]\nfn {fn_base}_request_rejects_unknown_keys_at_closed_objects() {{\n    \
                 support::unknown_keys_rejected({:?}, &[{list}]);\n}}\n",
                entry.fixtures.request
            ));
        }
    }

    // Family 3: declared error-envelope replay.
    for (position, case) in entry.fixtures.error_cases.iter().enumerate() {
        let setups = setup_list(&case.setup);
        out.push_str(&format!(
            "\n#[test]\nfn {fn_base}_error_case_{position}_envelope_matches() {{\n    \
             support::error_case_envelope_matches(&[{setups}], {:?}, {:?});\n}}\n",
            case.request, case.expected_error
        ));
    }

    // Family 4: replay observes only declared output tags.
    if entry.fixtures.replay_skip.is_none() {
        let declared = declared_output_tags(entry, fixtures_root)?;
        if !declared.is_empty() {
            let tags = declared
                .iter()
                .map(|tag| format!("{tag:?}"))
                .collect::<Vec<_>>()
                .join(", ");
            let setups = setup_list(&entry.fixtures.setup);
            out.push_str(&format!(
                "\n#[test]\nfn {fn_base}_replay_observes_a_declared_output() {{\n    \
                 support::replay_observes_declared(&[{setups}], {:?}, &[{tags}]);\n}}\n",
                entry.fixtures.request
            ));
        }
    }
    Ok(())
}

fn setup_list(setup: &[String]) -> String {
    setup
        .iter()
        .map(|path| format!("{path:?}"))
        .collect::<Vec<_>>()
        .join(", ")
}

fn response_fixtures(entry: &ResolvedCommand) -> Vec<String> {
    let mut fixtures = vec![entry.fixtures.response.clone()];
    for alternate in &entry.fixtures.responses {
        if !fixtures.contains(alternate) {
            fixtures.push(alternate.clone());
        }
    }
    fixtures
}

/// The output `type` tags this command's response fixtures declare.
fn declared_output_tags(entry: &ResolvedCommand, fixtures_root: &Path) -> Result<Vec<String>> {
    let mut tags = Vec::new();
    for fixture in response_fixtures(entry) {
        let value = read_fixture(fixtures_root, &fixture)?;
        if let Some(tag) = value.get("type").and_then(Value::as_str) {
            let tag = tag.to_owned();
            if !tags.contains(&tag) {
                tags.push(tag);
            }
        }
    }
    Ok(tags)
}

fn read_fixture(fixtures_root: &Path, relative: &str) -> Result<Value> {
    let path = fixtures_root.join(relative);
    let text = fs::read_to_string(&path).map_err(|source| IdlError::Read {
        path: path.clone(),
        source,
    })?;
    serde_json::from_str(&text).map_err(|source| IdlError::Json { path, source })
}

/// Traverses the request fixture alongside its derived schema and returns the JSON
/// pointers of every object node whose subschema is closed
/// (`additionalProperties: false`) — the sites where an injected unknown key
/// MUST be rejected. Open maps and user-payload subtrees (arbitrary JSON
/// documents, metadata maps) are skipped by construction, because their
/// subschemas are not closed. Conservative on `anyOf`/`oneOf`: recursion stops
/// where the subschema cannot be resolved unambiguously.
fn closed_object_sites(
    entry: &ResolvedCommand,
    document: &Value,
    fixtures_root: &Path,
) -> Result<Vec<String>> {
    let fixture = read_fixture(fixtures_root, &entry.fixtures.request)?;
    let defs = document.get("$defs");
    let Some(request_schema) = document.get("request") else {
        return Ok(Vec::new());
    };
    let mut sites = Vec::new();
    walk_closed_objects(&fixture, request_schema, defs, "", &mut sites);
    Ok(sites)
}

fn resolve_ref<'a>(schema: &'a Value, defs: Option<&'a Value>) -> &'a Value {
    if let Some(reference) = schema.get("$ref").and_then(Value::as_str) {
        if let Some(name) = reference.strip_prefix("#/$defs/") {
            if let Some(resolved) = defs.and_then(|defs| defs.get(name)) {
                return resolved;
            }
        }
    }
    schema
}

fn walk_closed_objects(
    value: &Value,
    schema: &Value,
    defs: Option<&Value>,
    pointer: &str,
    sites: &mut Vec<String>,
) {
    let schema = resolve_ref(schema, defs);
    match value {
        Value::Object(fields) => {
            if schema.get("additionalProperties") == Some(&Value::Bool(false)) {
                sites.push(pointer.to_owned());
            }
            let Some(properties) = schema.get("properties") else {
                return;
            };
            for (key, child) in fields {
                if let Some(child_schema) = properties.get(key) {
                    let child_pointer = format!("{pointer}/{}", escape_pointer_token(key));
                    walk_closed_objects(child, child_schema, defs, &child_pointer, sites);
                }
            }
        }
        Value::Array(items) => {
            let Some(item_schema) = schema.get("items") else {
                return;
            };
            for (position, item) in items.iter().enumerate() {
                let child_pointer = format!("{pointer}/{position}");
                walk_closed_objects(item, item_schema, defs, &child_pointer, sites);
            }
        }
        _ => {}
    }
}

fn escape_pointer_token(token: &str) -> String {
    token.replace('~', "~0").replace('/', "~1")
}

/// Whether injecting an unknown key at `site` of `fixture` is ACCEPTED by the
/// deserializer — true means the schema/deserializer divergence is still live.
fn unknown_key_is_accepted(fixture: &Value, site: &str) -> bool {
    let mut mutated = fixture.clone();
    let Some(target) = mutated.pointer_mut(site) else {
        return false;
    };
    let Some(object) = target.as_object_mut() else {
        return false;
    };
    object.insert("__tcp41_unknown_key__".to_owned(), Value::Bool(true));
    serde_json::from_value::<Command>(mutated).is_ok()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn copy_tree(source: &Path, destination: &Path) {
        fs::create_dir_all(destination).expect("scratch mkdir");
        for entry in fs::read_dir(source).expect("scratch read_dir") {
            let entry = entry.expect("scratch entry");
            let target = destination.join(entry.file_name());
            if entry.file_type().expect("scratch file_type").is_dir() {
                copy_tree(&entry.path(), &target);
            } else {
                fs::copy(entry.path(), &target).expect("scratch copy");
            }
        }
    }

    /// End-to-end on a hermetic scratch copy of the IDL tree: a bogus
    /// generated file must be detected as stale (kills a no-op
    /// `check_tests`), and a real generation must repair it (kills a no-op
    /// `generate_tests` — the bogus file would survive and fail the recheck).
    #[test]
    fn generate_then_check_roundtrip_on_a_scratch_root() {
        let real = super::super::default_repo_root();
        let scratch = tempfile::tempdir().expect("scratch root");
        for relative in ["crates/executor/idl/v1", "crates/executor/tests/fixtures"] {
            copy_tree(&real.join(relative), &scratch.path().join(relative));
        }
        // The resolver also scans the enum sources for variant coverage.
        let src = scratch.path().join("crates/executor/src");
        fs::create_dir_all(&src).expect("scratch src dir");
        for file in ["command.rs", "output.rs"] {
            fs::copy(real.join("crates/executor/src").join(file), src.join(file))
                .expect("copy enum source");
        }
        let generated = generated_tests_path(scratch.path());
        fs::create_dir_all(generated.parent().expect("parent")).expect("mkdir generated");
        fs::write(&generated, "// bogus\n").expect("seed bogus file");
        match check_tests(scratch.path()) {
            Err(IdlError::Stale { .. }) => {}
            other => panic!("a bogus generated file must be reported stale, got: {other:?}"),
        }
        generate_tests(scratch.path()).expect("generate on the scratch root");
        check_tests(scratch.path()).expect("fresh after a real generation");
    }

    /// The committed generated suite byte-matches a fresh generation — the
    /// in-`cargo-test` twin of the `check-tests` CI gate, and the kill switch
    /// for every mutant in this emitter: any change to what is emitted (or to
    /// the site walk, or to the divergence-ledger enforcement) produces a
    /// different file, or an error, and fails here.
    #[test]
    fn committed_conformance_suite_is_fresh() {
        check_tests(&super::super::default_repo_root())
            .expect("generated conformance suite must be fresh");
    }

    /// The divergence probe tells accepted from rejected: a closed command
    /// object rejects an injected top-level key — including the empty-payload
    /// commands since #2739's fix — while an open user-payload subtree (a
    /// JSON document body) legitimately accepts one.
    #[test]
    fn the_divergence_probe_distinguishes_closed_from_open() {
        let closed = serde_json::json!({"type": "kv_put", "key": "YQ==", "value": "b25l"});
        assert!(!unknown_key_is_accepted(&closed, ""));
        // The #2739 regression pin: empty-payload commands are closed too.
        let empty_payload = serde_json::json!({"type": "ping"});
        assert!(!unknown_key_is_accepted(&empty_payload, ""));
        let open_payload =
            serde_json::json!({"type": "json_set", "key": "k", "path": "$", "value": {"a": 1}});
        assert!(unknown_key_is_accepted(&open_payload, "/value"));
    }
}
