use crate::support::*;

#[allow(clippy::too_many_lines)]
pub(super) fn graph_commands() -> Vec<Command> {
    vec![
        Command::GraphCreate {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
        },
        Command::GraphDelete {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            force: false,
        },
        Command::GraphList {
            branch: None,
            space: None,
            cursor: Some("deps".to_owned()),
            limit: Some(5),
            as_of: None,
            as_of_time: None,
        },
        Command::GraphGetMeta {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            as_of: None,
            as_of_time: None,
        },
        Command::GraphAddNode {
            object_type: None,
            branch: Some("feature".to_owned()),
            space: Some("space-a".to_owned()),
            graph: "deps".to_owned(),
            node_id: "node-a".to_owned(),
            properties: Some(json!({"kind": "root"})),
            binding: Some(graph_binding()),
        },
        Command::GraphGetNode {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            node_id: "node-a".to_owned(),
            as_of: None,
            as_of_time: None,
        },
        Command::GraphRemoveNode {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            node_id: "node-a".to_owned(),
        },
        Command::GraphListNodes {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            prefix: Some("node-".to_owned()),
            cursor: Some("node-a".to_owned()),
            limit: Some(5),
            as_of: None,
            as_of_time: None,
        },
        Command::GraphAddEdge {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            src: "node-a".to_owned(),
            edge_type: "depends_on".to_owned(),
            dst: "node-b".to_owned(),
            weight: Some(2.5),
            properties: Some(json!({"source": "test"})),
        },
        Command::GraphGetEdge {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            src: "node-a".to_owned(),
            edge_type: "depends_on".to_owned(),
            dst: "node-b".to_owned(),
            as_of: None,
            as_of_time: None,
        },
        Command::GraphRemoveEdge {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            src: "node-a".to_owned(),
            edge_type: "depends_on".to_owned(),
            dst: "node-b".to_owned(),
        },
        Command::GraphNeighbors {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            node_id: "node-a".to_owned(),
            direction: GraphDirection::Outgoing,
            edge_type: Some("depends_on".to_owned()),
            cursor: None,
            limit: Some(5),
            as_of: None,
            as_of_time: None,
        },
        Command::GraphBindingsForEntity {
            branch: None,
            space: None,
            target: graph_binding_target(),
            cursor: None,
            limit: Some(5),
            as_of: None,
            as_of_time: None,
        },
        Command::GraphBatchWrite {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            operations: Vec::new(),
        },
        Command::GraphDefineObjectType {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            name: "Document".to_owned(),
            properties: [(
                "title".to_owned(),
                GraphPropertyDef::new(Some("string".to_owned()), true),
            )]
            .into_iter()
            .collect(),
        },
        Command::GraphDefineLinkType {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            name: "wrote".to_owned(),
            source: "Author".to_owned(),
            target: "Document".to_owned(),
            cardinality: Some("one-to-many".to_owned()),
            properties: std::collections::BTreeMap::new(),
        },
        Command::GraphDeleteObjectType {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            name: "Document".to_owned(),
        },
        Command::GraphDeleteLinkType {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            name: "wrote".to_owned(),
        },
        Command::GraphFreezeOntology {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
        },
        Command::GraphGetOntology {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            as_of: Some(9),
            as_of_time: None,
        },
        Command::GraphOntologySummary {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            as_of: None,
            as_of_time: None,
        },
        Command::GraphNodesByType {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            object_type: "Document".to_owned(),
            cursor: Some("node-a".to_owned()),
            limit: Some(5),
            as_of: None,
            as_of_time: None,
        },
        Command::GraphWcc {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            budget: None,
            as_of: None,
            as_of_time: None,
        },
        Command::GraphLcc {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            budget: None,
            as_of: Some(9),
            as_of_time: None,
        },
        Command::GraphSssp {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            source: "node-a".to_owned(),
            direction: Some(GraphDirection::Both),
            budget: None,
            as_of: None,
            as_of_time: None,
        },
        Command::GraphPagerank {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            damping: Some(0.9),
            max_iterations: Some(50),
            tolerance: None,
            personalization: None,
            budget: None,
            as_of: None,
            as_of_time: None,
        },
        Command::GraphCdlp {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            max_iterations: Some(5),
            direction: None,
            budget: None,
            as_of: None,
            as_of_time: None,
        },
        Command::GraphBfs {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            start: "node-a".to_owned(),
            max_depth: Some(3),
            max_nodes: None,
            edge_types: None,
            direction: None,
            budget: None,
            as_of: None,
            as_of_time: None,
        },
        Command::GraphApplyDeletePolicy {
            branch: None,
            space: None,
            target: graph_binding_target(),
            policy: GraphDeletePolicy::Detach,
        },
        Command::GraphBulkInsert {
            branch: None,
            space: None,
            graph: "deps".to_owned(),
            nodes: vec![GraphBulkNode::new(
                "node-a".to_owned(),
                Some(json!({"kind": "doc"})),
                Some(graph_binding()),
                Some("Document".to_owned()),
            )],
            edges: vec![GraphBulkEdge::new(
                "node-a".to_owned(),
                "depends_on".to_owned(),
                "node-b".to_owned(),
                Some(2.5),
                None,
            )],
            chunk_size: Some(1000),
        },
    ]
}

#[allow(clippy::too_many_lines)]
pub(super) fn graph_round_trip_edge_commands() -> Vec<Command> {
    vec![
        Command::GraphCreate {
            branch: Some("feature".to_owned()),
            space: Some("space-a".to_owned()),
            graph: "wide".to_owned(),
        },
        Command::GraphAddNode {
            object_type: None,
            branch: Some("feature".to_owned()),
            space: Some("space-a".to_owned()),
            graph: "wide".to_owned(),
            node_id: "node-empty".to_owned(),
            properties: Some(json!({})),
            binding: None,
        },
        Command::GraphAddEdge {
            branch: Some("feature".to_owned()),
            space: Some("space-a".to_owned()),
            graph: "wide".to_owned(),
            src: "node-a".to_owned(),
            edge_type: "relates_to".to_owned(),
            dst: "node-b".to_owned(),
            weight: None,
            properties: None,
        },
        Command::GraphNeighbors {
            branch: Some("feature".to_owned()),
            space: Some("space-a".to_owned()),
            graph: "wide".to_owned(),
            node_id: "node-a".to_owned(),
            direction: GraphDirection::Incoming,
            edge_type: None,
            cursor: Some("cursor".to_owned()),
            limit: Some(0),
            as_of: None,
            as_of_time: None,
        },
        Command::GraphNeighbors {
            branch: Some("feature".to_owned()),
            space: Some("space-a".to_owned()),
            graph: "wide".to_owned(),
            node_id: "node-a".to_owned(),
            direction: GraphDirection::Both,
            edge_type: Some("relates_to".to_owned()),
            cursor: None,
            limit: Some(1),
            as_of: None,
            as_of_time: None,
        },
        Command::GraphBatchWrite {
            branch: Some("feature".to_owned()),
            space: Some("space-a".to_owned()),
            graph: "wide".to_owned(),
            operations: vec![
                GraphBatchOperation::UpsertNode {
                    node_id: "node-a".to_owned(),
                    data: GraphNodeData::new(None, Some(graph_binding())),
                },
                GraphBatchOperation::DeleteNode {
                    node_id: "node-old".to_owned(),
                },
                GraphBatchOperation::UpsertEdge {
                    src: "node-a".to_owned(),
                    edge_type: "relates_to".to_owned(),
                    dst: "node-b".to_owned(),
                    data: GraphEdgeData::new(Some(1.25), Some(json!({"batch": true}))),
                },
                GraphBatchOperation::DeleteEdge {
                    src: "node-a".to_owned(),
                    edge_type: "relates_to".to_owned(),
                    dst: "node-b".to_owned(),
                },
            ],
        },
        Command::GraphPagerank {
            branch: Some("feature".to_owned()),
            space: Some("space-a".to_owned()),
            graph: "wide".to_owned(),
            damping: Some(0.5),
            max_iterations: Some(100),
            tolerance: Some(1e-8),
            personalization: Some(
                [("node-a".to_owned(), 5.0), ("node-b".to_owned(), 3.0)]
                    .into_iter()
                    .collect(),
            ),
            budget: Some(GraphAnalyticsBudget::new(Some(1_000), Some(10_000))),
            as_of: Some(77),
            as_of_time: None,
        },
        Command::GraphBfs {
            branch: Some("feature".to_owned()),
            space: Some("space-a".to_owned()),
            graph: "wide".to_owned(),
            start: "node-a".to_owned(),
            max_depth: Some(2),
            max_nodes: Some(100),
            edge_types: Some(vec!["depends_on".to_owned(), "relates_to".to_owned()]),
            direction: Some(GraphDirection::Both),
            budget: Some(GraphAnalyticsBudget::new(None, Some(500))),
            as_of: None,
            as_of_time: None,
        },
        Command::GraphWcc {
            branch: Some("feature".to_owned()),
            space: Some("space-a".to_owned()),
            graph: "wide".to_owned(),
            budget: Some(GraphAnalyticsBudget::new(Some(10), None)),
            as_of: Some(31),
            as_of_time: None,
        },
    ]
}

pub(super) fn graph_binding_target_round_trip_commands() -> Vec<Command> {
    [
        GraphBindingPrimitive::Kv,
        GraphBindingPrimitive::Json,
        GraphBindingPrimitive::Vector,
        GraphBindingPrimitive::Event,
        GraphBindingPrimitive::Graph,
    ]
    .into_iter()
    .enumerate()
    .map(|(index, primitive)| Command::GraphBindingsForEntity {
        branch: Some("feature".to_owned()),
        space: Some("space-a".to_owned()),
        target: GraphBindingTarget::new(
            primitive,
            (index % 2 == 0).then(|| "entity-branch".to_owned()),
            "entity-space",
            format!("entity-{index}"),
        ),
        cursor: Some(format!("cursor-{index}")),
        limit: Some(10),
        as_of: None,
        as_of_time: None,
    })
    .collect()
}
